# Generated by Django 5.0.3 on 2024-03-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='created_by',
        ),
    ]
